GAME_TIMELINE = {
  {time = 4, enemies = {{type = "straight", x = 288, y = -30}}},
  {time = 4, enemies = {{type = "sideways", x = 1, y = 288}}},
  {time = 4, enemies = {{type = "straight", x = 160, y = -30}, {type = "straight", x = 416, y = -30}}},
  {time = 6, enemies = {{type = "pendulum", x = 200, y = -30}}},
  {time = 2, enemies = {{type = "pendulum", x = 200, y = -30}}},
  {time = 2, enemies = {{type = "pendulum", x = 200, y = -30}}},
  {time = 2, enemies = {{type = "pendulum", x = 200, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 288, y = -30}, {type = "straight", x = 192, y = -30}, {type = "straight", x = 384, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 160, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 224, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 288, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 352, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 416, y = -30}}},
  {time = 4, enemies = {{type = "sideways", x = 1, y = 32}, {type = "sideways", x = 1, y = 96}, {type = "sideways", x = -1, y = 64}, {type = "sideways", x = -1, y = 128}}},
  {time = 2, enemies = {{type = "sideways", x = 1, y = 128}, {type = "sideways", x = 1, y = 192}, {type = "sideways", x = -1, y = 160}, {type = "sideways", x = -1, y = 96}}},
  {time = 2, enemies = {{type = "sideways", x = 1, y = 224}, {type = "sideways", x = 1, y = 288}, {type = "sideways", x = -1, y = 192}, {type = "sideways", x = -1, y = 256}}},
  {time = 4, enemies = {{type = "straight", x = 288, y = -30}}},
  {time = 6, enemies = {{type = "pendulum", x = 0, y = -30}}},
  {time = 0.5, enemies = {{type = "pendulum", x = 0, y = -30}}},
  {time = 0.5, enemies = {{type = "pendulum", x = 0, y = -30}}},
  {time = 0.5, enemies = {{type = "pendulum", x = 0, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 160, y = -30}, {type = "straight", x = 416, y = -30}}},
  {time = 0.5, enemies = {{type = "straight", x = 160, y = -30}, {type = "straight", x = 416, y = -30}}},
  -- 1 Minute
  {time = 0.5, enemies = {{type = "straight", x = 160, y = -30}, {type = "straight", x = 416, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 160, y = -30}, {type = "straight", x = 416, y = -30}, {type = "pendulum", x = 200, y = -30}}},
  {time = 2, enemies = {{type = "sideways", x = 1, y = 128}, {type = "sideways", x = 1, y = 128}}},
  {time = 5, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 576, y = -30}}},
  {time = 4, enemies = {{type = "sideways", x = -1, y = 384}}},
  {time = 0.25, enemies = {{type = "sideways", x = -1, y = 352}}},
  {time = 0.25, enemies = {{type = "sideways", x = -1, y = 320}}},
  {time = 0.25, enemies = {{type = "sideways", x = -1, y = 288}}},
  {time = 0.25, enemies = {{type = "sideways", x = -1, y = 256}}},
  {time = 0.25, enemies = {{type = "sideways", x = -1, y = 224}}},
  {time = 0.25, enemies = {{type = "sideways", x = -1, y = 192}}},
  {time = 4, enemies = {{type = "sideways", x = 1, y = 384}}},
  {time = 0.25, enemies = {{type = "sideways", x = 1, y = 352}}},
  {time = 0.25, enemies = {{type = "sideways", x = 1, y = 320}}},
  {time = 0.25, enemies = {{type = "sideways", x = 1, y = 288}}},
  {time = 0.25, enemies = {{type = "sideways", x = 1, y = 256}}},
  {time = 0.25, enemies = {{type = "sideways", x = 1, y = 224}}},
  {time = 0.25, enemies = {{type = "sideways", x = 1, y = 192}}},
  {time = 4, enemies = {{type = "straight", x = 160, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 160, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 160, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 160, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 416, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 416, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 416, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 416, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 416, y = -30}, {type = "straight", x = 160, y = -30}, {type = "straight", x = 288, y = -30}}},
  {time = 3, enemies = {{type = "straight", x = 416, y = -30}, {type = "straight", x = 160, y = -30}, {type = "straight", x = 288, y = -30}}},
  {time = 3, enemies = {{type = "straight", x = 416, y = -30}, {type = "straight", x = 160, y = -30}, {type = "straight", x = 288, y = -30}}},
  {time = 5.5, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 576, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 576, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 576, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 576, y = -30}}},
  {time = 3, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 576, y = -30}, {type = "pendulum", x = 288, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 576, y = -30}, {type = "pendulum", x = 288, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 576, y = -30}, {type = "pendulum", x = 288, y = -30}}},
  -- 2 Minutes
  {time = 4, enemies = {{type = "straight", x = 576, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 544, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 512, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 480, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 448, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 416, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 384, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 352, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 320, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 288, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 0, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 32, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 64, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 96, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 128, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 160, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 192, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 224, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 256, y = -30}}},
  {time = 1, enemies = {{type = "straight", x = 288, y = -30}}},
  {time = 6, enemies = {{type = "sideways", x = 1, y = 480}, {type = "sideways", x = -1, y = 480}}},
  {time = 1, enemies = {{type = "sideways", x = 1, y = 416}, {type = "sideways", x = -1, y = 416}}},
  {time = 1, enemies = {{type = "sideways", x = 1, y = 352}, {type = "sideways", x = -1, y = 352}}},
  {time = 1, enemies = {{type = "sideways", x = 1, y = 288}, {type = "sideways", x = -1, y = 288}}},
  {time = 1, enemies = {{type = "sideways", x = 1, y = 224}, {type = "sideways", x = -1, y = 224}}},
  {time = 1, enemies = {{type = "sideways", x = 1, y = 160}, {type = "sideways", x = -1, y = 160}}},
  {time = 1, enemies = {{type = "sideways", x = 1, y = 96}, {type = "sideways", x = -1, y = 96}}},
  {time = 1, enemies = {{type = "sideways", x = 1, y = 32}, {type = "sideways", x = -1, y = 32}}},
  {time = 6, enemies = {{type = "pendulum", x = 0, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 32, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 64, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 96, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 128, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 160, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 192, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 224, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 256, y = -30}}},
  {time = 1, enemies = {{type = "pendulum", x = 288, y = -30}}},
  {time = 6, enemies = {{type = "pendulum", x = 0, y = -30}, {type = "pendulum", x = 32, y = -30}, {type = "pendulum", x = 64, y = -30}, {type = "pendulum", x = 96, y = -30}, {type = "pendulum", x = 128, y = -30}}},
  -- 3 Minutes
}

--{time = 2, enemies = {{type = "straight", x = 100, y = -30}}},
--{time = 2, enemies = {{type = "pendulum", x = 200, y = -30}}},
--{time = 2, enemies = {{type = "sideways", x = 1, y = 288}}}