GAME_TIMELINE = {
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}},
  {time = 4, enemies = {{type = "straight", x = 284, y = -30}}}
}

--{time = 2, enemies = {{type = "straight", x = 100, y = -30}}},
--{time = 2, enemies = {{type = "straight", x = 200, y = -30}, {type = "straight", x = 400, y = -30}}},
--{time = 2, enemies = {{type = "pendulum", x = 200, y = -30}, {type = "straight", x = 400, y = -30}}},
--{time = 2, enemies = {{type = "sideways", x = 1, y = 284}, {type = "sideways", x = -1, y = 350}}}